[Default_Theme]
name = "Default Theme"
ico = "icons.toml"
qss = "default.qss"
param = "default.param"

[Dark_Theme_1]
name = "Dark Theme 1"
param = "dark1.param"

[Dark_Theme_2]
name = "Dark Theme 2"
param = "dark2.param"

[Default_Theme_Big]
name = "Default Theme-Big"
param = "default.param"
extra = "big.param"

[Dark_Theme_1_Big]
name = "Dark Theme 1-Big"
param = "dark1.param"
extra = "big.param"

[Dark_Theme_2_Big]
name = "Dark Theme 2-Big"
param = "dark2.param"
extra = "big.param"
