[Default_Theme]
name = "Default Theme"
ico = "icons.toml"
qss = "default.qss"
param = "default.param"

[dark_1]
name = "Dark 1"
param = "dark1.param"

[dark_2]
name = "Dark 2"
param = "dark2.param"

[sand_brown]
name = "Sand Brown"
param = "sand_brown.param"

[brown]
name = "Brown"
param = "brown.param"

[deep_blue]
name = "Deep Blue"
param = "deep_blue.param"

[dark_green]
name = "Dark Green"
param = "dark_green.param"
