# Form implementation generated from reading ui file 'c:\Users\mihal\OneDrive\Documents\pyprj\fileo\src\fileo\widgets\notes.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FileNotes(object):
    def setupUi(self, FileNotes):
        FileNotes.setObjectName("FileNotes")
        FileNotes.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileNotes)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(FileNotes)
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tagEdit = QtWidgets.QLineEdit(self.header)
        self.tagEdit.setFrame(False)
        self.tagEdit.setObjectName("tagEdit")
        self.horizontalLayout.addWidget(self.tagEdit)
        self.plus = QtWidgets.QToolButton(self.header)
        self.plus.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.plus.setAutoRaise(True)
        self.plus.setObjectName("plus")
        self.horizontalLayout.addWidget(self.plus)
        self.info = QtWidgets.QToolButton(self.header)
        self.info.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup)
        self.info.setAutoRaise(True)
        self.info.setObjectName("info")
        self.horizontalLayout.addWidget(self.info)
        self.verticalLayout.addWidget(self.header)
        self.browser = QtWidgets.QTextBrowser(FileNotes)
        self.browser.setObjectName("browser")
        self.verticalLayout.addWidget(self.browser)

        self.retranslateUi(FileNotes)
        QtCore.QMetaObject.connectSlotsByName(FileNotes)

    def retranslateUi(self, FileNotes):
        _translate = QtCore.QCoreApplication.translate
        FileNotes.setWindowTitle(_translate("FileNotes", "Form"))
        self.tagEdit.setPlaceholderText(_translate("FileNotes", "input file tags here (separated by commas), or doubleclick to select in the appeared list"))
        self.plus.setToolTip(_translate("FileNotes", "add note"))
        self.plus.setText(_translate("FileNotes", "..."))
        self.info.setToolTip(_translate("FileNotes", "Show file info"))
        self.info.setText(_translate("FileNotes", "..."))
