# Form implementation generated from reading ui file 'c:\Users\mihal\OneDrive\Documents\pyprj\fileo-G\fileo\src\widgets\dt_editor.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dtSetter(object):
    def setupUi(self, dtSetter):
        dtSetter.setObjectName("dtSetter")
        dtSetter.resize(244, 91)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dtSetter)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dlg_frame = QtWidgets.QFrame(parent=dtSetter)
        self.dlg_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dlg_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dlg_frame.setObjectName("dlg_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dlg_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.dlg_frame)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.dlg_frame)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout.addWidget(self.timeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ok = QtWidgets.QPushButton(parent=self.dlg_frame)
        self.ok.setObjectName("ok")
        self.horizontalLayout_2.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(parent=self.dlg_frame)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.dlg_frame)

        self.retranslateUi(dtSetter)
        QtCore.QMetaObject.connectSlotsByName(dtSetter)

    def retranslateUi(self, dtSetter):
        _translate = QtCore.QCoreApplication.translate
        dtSetter.setWindowTitle(_translate("dtSetter", "Form"))
        self.dateEdit.setDisplayFormat(_translate("dtSetter", "yyyy-MM-dd"))
        self.timeEdit.setDisplayFormat(_translate("dtSetter", "hh:mm:ss"))
        self.ok.setText(_translate("dtSetter", "Ok"))
        self.cancel.setText(_translate("dtSetter", "Cancel"))
