# Form implementation generated from reading ui file 'c:\Users\mihal\OneDrive\Documents\pyprj\fileo-G\fileo\src\widgets\theme_list.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_themeList(object):
    def setupUi(self, themeList):
        themeList.setObjectName("themeList")
        themeList.resize(232, 245)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(themeList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dlg_frame = QtWidgets.QFrame(parent=themeList)
        self.dlg_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dlg_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dlg_frame.setObjectName("dlg_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dlg_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.theme_list = QtWidgets.QListWidget(parent=self.dlg_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theme_list.sizePolicy().hasHeightForWidth())
        self.theme_list.setSizePolicy(sizePolicy)
        self.theme_list.setObjectName("theme_list")
        self.verticalLayout.addWidget(self.theme_list)
        self.log_theme = QtWidgets.QCheckBox(parent=self.dlg_frame)
        self.log_theme.setObjectName("log_theme")
        self.verticalLayout.addWidget(self.log_theme)
        self.verticalLayout_2.addWidget(self.dlg_frame)

        self.retranslateUi(themeList)
        QtCore.QMetaObject.connectSlotsByName(themeList)

    def retranslateUi(self, themeList):
        _translate = QtCore.QCoreApplication.translate
        themeList.setWindowTitle(_translate("themeList", "Form"))
        self.log_theme.setText(_translate("themeList", "save color theme log"))
